In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import tensorflow as tf

In [2]:
import time

In [3]:
from spellchecker import SpellChecker

In [4]:
from wordcloud import STOPWORDS, WordCloud

In [20]:
df = pd.read_csv(r'C:\Users\Vinayak Sidharth\Documents\twitter//train.csv', encoding = 'latin-1')

In [21]:
df.head(4)

target          id                          date      flag  \
0       0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY   
1       0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
2       0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
3       0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   

              user                                               text  
0  _TheSpecialOne_  @switchfoot http://twitpic.com/2y1zl - Awww, t...  
1    scotthamilton  is upset that he can't update his Facebook by ...  
2         mattycus  @Kenichan I dived many times for the ball. Man...  
3          ElleCTF    my whole body feels itchy and like its on fire

In [22]:
df.drop(['flag'],axis=1, inplace = True)

In [23]:
users = np.array(df['user'].unique() )

In [24]:
all_text = np.array(df['text'].values)

In [25]:
target_val = np.array(df['target'].values)

In [26]:
def ttarg(i,df):
    print('{}_is the target\n'.format(np.array(df['target'].values)[i]))
    print(np.array(df['text'].values)[i])
    

In [27]:
df_1 = df.sample(frac=1, random_state = 43)
df_1['text'] = df_1['text'].apply(str)

In [28]:
ttarg(10,df_1)

4_is the target

so they WON YEAH!! a little late cause i kept rewinding the dang thing 


In [29]:
df['target'].unique()

array([0, 4], dtype=int64)

In [30]:
def poss(val):
    if val == 4:
        res = 1
    else :
        res = 0
    return res

In [31]:
df_1['target'] = df_1['target'].apply(lambda x : poss(x))

In [32]:
text_0 = np.array(df_1.loc[df_1['target']==0]['text'].values)
text_1 = np.array(df_1.loc[df_1['target']==1]['text'].values)

In [33]:
X_1 = df_1.text.values

In [34]:
y = df_1.target.values

In [35]:
text_0

array(["@speakforme I know. We should go asap. like when we get back home I wanna buy jeans, too. But I'm too fat for jeans. ",
       '@Lisa_Nova we had it but we lost it  very sad 4 us cause we loved it',
       "I would've wifed @KiyastarW ... if only she would have me! ", ...,
       'locked out of my outlook account for the 3rd time in 3 days ',
       "Ugh. Slept 'til now. My cold hath blossomed during the night. ",
       '@sourapplemedia is that coffee house at City Center?  I miss the Italian Ice shop next door '],
      dtype=object)

In [36]:
ttarg(222,df_1)

1_is the target

@winniedepoohi it was good .. but not better than the time we had 


In [38]:
STOPWORDS.add('ibm')

In [39]:
def correct_txt(text):
    final = []
    final2 = []
    for num,i in enumerate(text):
        lower = []
        word_arr = i.split()
        for j in word_arr:
            lower.append(j.lower())
        
        spell = SpellChecker()
        misspelled = spell.unknown(lower)
        
        for word in misspelled:
            lower.remove(word)
            lower.append(spell.correction(word))
        final.append(lower)
        num = num + 1

    
            
    for j in final:
        final2.append(list(filter(lambda x: x[0]!= '@', j)))
        
        
    return final, final2
        
        

In [40]:
def correct_notxt(text):
    final = []
    final2 = []
    for num,i in enumerate(text):
        lower = []
        word_arr = i.split()
        for j in word_arr:
            lower.append(j.lower())
        final.append(lower)
            
        num = num + 1
        if num %100000 ==0:
            print('{}/{}'.format(num,len(text)))
            
    for j in final:
        final2.append(list(filter(lambda x: x[0]!= '@', j)))
        
        
    return final, final2
            
    

In [41]:
def combine_array(popo):
    coom = []
    for i in popo:
        for j in i:
            coom.append(j)
    print('task 2 over')
    return coom

In [42]:
def plot_cloud(stop, arr):
    das = ' '
    sten = das.join(arr)
    
    cloud = WordCloud(width = 3000, height = 2000, random_state=1, background_color='salmon',
                          colormap='Pastel1', collocations=False, stopwords = stop)
    cloud.generate(sten)
    
    print('GENERATED')
    
    plt.figure(figsize=(17,8))
    plt.axis('off')
    plt.imshow(cloud)

    return sten
    

In [43]:
def master_plot(array):
    trash,wordz = correct_notxt(array)
    real_wordz = combine_array(wordz)
    plot_cloud(STOPWORDS,real_wordz )


In [87]:
def acc(y1,y2):
    new = []
    for j in y1:
        if j >=0.5:
            new.append(1)
        else:
            new.append(0)
    call = 0
    for i,val in enumerate(ytest):
        if val==new[i]:
            call = call+1
            
    return call/len(y1)
        

In [44]:
#texx_1 = text_1[:20]
#texx_0 = text_0[:20]

In [45]:
#master_plot(texx_1)

In [46]:
#master_plot(texx_0)

In [47]:
#u,i = correct_notxt(text_1)

In [48]:
#nonspell= i

In [49]:
#master_plot(text_1)

In [50]:
#master_plot(text_0)

In [51]:
noval , X_2 = correct_notxt(X_1)

100000/1600000
200000/1600000
300000/1600000
400000/1600000
500000/1600000
600000/1600000
700000/1600000
800000/1600000
900000/1600000
1000000/1600000
1100000/1600000
1200000/1600000
1300000/1600000
1400000/1600000
1500000/1600000
1600000/1600000


In [52]:
cc = []
for i,val in enumerate(X_2):
    if len(val) == 0:
        cc.append(i)

In [53]:
cc

[671,
 1050,
 1312,
 1387,
 1701,
 1936,
 2832,
 3064,
 3182,
 3296,
 3543,
 3707,
 4006,
 5054,
 6177,
 6489,
 6632,
 6957,
 7990,
 8228,
 8345,
 8588,
 8640,
 9546,
 9817,
 11070,
 11784,
 12734,
 13142,
 13188,
 14662,
 16298,
 18161,
 19000,
 19120,
 19639,
 20070,
 20368,
 21164,
 21196,
 21257,
 22362,
 22681,
 22763,
 23828,
 24396,
 25473,
 26343,
 28716,
 28860,
 29075,
 29371,
 29450,
 29614,
 33594,
 34356,
 34840,
 35218,
 35755,
 36371,
 36808,
 38373,
 39517,
 40065,
 40725,
 41991,
 42158,
 42359,
 43040,
 44252,
 45183,
 45280,
 45384,
 46186,
 46657,
 47527,
 47888,
 47953,
 48446,
 48650,
 49030,
 49329,
 49604,
 50422,
 50959,
 51180,
 51743,
 52489,
 52619,
 52840,
 54719,
 56945,
 57268,
 58953,
 59004,
 59896,
 60167,
 60773,
 60849,
 61490,
 61712,
 61965,
 62295,
 62833,
 67100,
 67752,
 68039,
 68045,
 68168,
 68199,
 69451,
 69833,
 72083,
 72442,
 72472,
 72878,
 73411,
 74583,
 74848,
 75437,
 76937,
 77028,
 77303,
 77368,
 78440,
 78910,
 79206,
 80100,
 8

In [54]:
rmove = np.array(X_1)[cc]

In [55]:
X_2 = np.delete(X_2, cc)
y = np.delete(y, cc)

In [56]:
len(X_2)

1597258

In [57]:
len(y)

1597258

In [58]:
tst_size = 100000
X_test = X_2[-tst_size:]
y_test = y[-tst_size:]
X_train = X_2[:len(X_2)-tst_size]
y_train = y[:len(y)-tst_size]

In [59]:
inn = tf.keras.preprocessing.text.Tokenizer(num_words = 60000)

In [60]:
inn.fit_on_texts(X_train)

In [61]:
pp = inn.word_index.items()

In [62]:
X_train = inn.texts_to_sequences(X_train)

In [63]:
X_test = inn.texts_to_sequences(X_test)

In [64]:
pad_sequences = tf.keras.preprocessing.sequence.pad_sequences

In [65]:
X_pad_tr = pad_sequences(X_train , maxlen = 57)
X_pad_ts = pad_sequences(X_test , maxlen = 57)

In [66]:
X_pad_tr.shape

(1497258, 57)

In [67]:
tr=[]
ts=[]
for i,val in enumerate(X_train):
    if len(val)==0:
        tr.append(i)
for j,xa in enumerate(X_test):
    if len(xa)==0:
        ts.append(j)

In [68]:
X_pad_tr = np.array(X_pad_tr)
X_pad_ts = np.array(X_pad_ts)

In [69]:
X_pad_tr= np.delete(X_pad_tr, tr,0)
X_pad_ts= np.delete(X_pad_ts, ts,0)

In [70]:
y_train = np.delete(y_train, tr)
y_test = np.delete(y_test, ts)

In [71]:
print('x train = {}, y_train = {} , x_test = {}, y_test = {}'.format(X_pad_tr.shape, y_train.shape,X_pad_ts.shape, y_test.shape ))

x train = (1493300, 57), y_train = (1493300,) , x_test = (99735, 57), y_test = (99735,)


In [8]:
import pickle

In [73]:
with open ('xtrain.pickle','w+b') as f:
    pickle.dump(X_pad_tr, f)

In [74]:
with open ('ytrain.pickle','w+b') as f:
    pickle.dump(y_train, f)

In [75]:
with open ('xtest.pickle','w+b') as f:
    pickle.dump(X_pad_ts, f)

In [76]:
with open ('ytest.pickle','w+b') as f:
    pickle.dump(y_test, f)

In [9]:
with open ('xtrain.pickle','r+b') as f:
    xtrain= pickle.load( f)

In [10]:
with open ('ytrain.pickle','r+b') as f:
    ytrain= pickle.load( f)

In [11]:
with open ('xtest.pickle','r+b') as f:
    xtest= pickle.load( f)

In [12]:
with open ('ytest.pickle','r+b') as f:
    ytest= pickle.load( f)

In [13]:
ytest.shape

(99735,)

In [14]:
xtest.shape

(99735, 57)

In [15]:
xtrain.shape

(1493300, 57)

In [16]:
ytrain.shape

(1493300,)

In [40]:
valsize = 300000

In [59]:
#val = xtrain[:valsize]
#yval = ytrain[:valsize]
#xtrain = xtrain[valsize:]
#ytrain = ytrain[valsize :]



In [63]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Embedding(60000, 32))
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)))
model.add(tf.keras.layers.Dense(64, activation = 'relu'))
model.add(tf.keras.layers.Dense(1, activation = 'sigmoid'))

In [64]:
model.compile(optimizer = 'adam', metrics=['accuracy'], loss='binary_crossentropy' )

In [65]:
fitted = model.fit(xtrain, ytrain,  validation_split = 0.28, epochs = 5)

Train on 1075176 samples, validate on 418124 samples
Epoch 1/5
1075176/1075176 [==============================] - 2148s 2ms/sample - loss: 0.4201 - accuracy: 0.8063 - val_loss: 0.3915 - val_accuracy: 0.8230
Epoch 2/5
1075176/1075176 [==============================] - 2251s 2ms/sample - loss: 0.3625 - accuracy: 0.8390 - val_loss: 0.3841 - val_accuracy: 0.8270
Epoch 3/5
1075176/1075176 [==============================] - 2345s 2ms/sample - loss: 0.3292 - accuracy: 0.8573 - val_loss: 0.3876 - val_accuracy: 0.8264
Epoch 4/5
1075176/1075176 [==============================] - 4206s 4ms/sample - loss: 0.2992 - accuracy: 0.8730 - val_loss: 0.4026 - val_accuracy: 0.8208
Epoch 5/5
1075176/1075176 [==============================] - 3665s 3ms/sample - loss: 0.2711 - accuracy: 0.8874 - val_loss: 0.4227 - val_accuracy: 0.8155


In [66]:
model.save(r'C:\Users\Vinayak Sidharth\Documents\TWITTER_HAPPINESS.model')

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: C:\Users\Vinayak Sidharth\Documents\TWITTER_HAPPINESS.model\assets


In [69]:
print('JUST STOP ON 2 EPCOH IT IS THE BEST ONE DO IT LAST ONE YOU DO THE RETARDED ALL THE OTHER SHIT BRO')

JUST STOP ON 2 EPCOH IT IS THE BEST ONE DO IT LAST ONE YOU DO THE RETARDED ALL THE OTHER SHIT BRO


In [83]:
pred = model.predict(xtest)

In [88]:
acc(pred,ytest)

0.8126234521481928

In [120]:
fit = 100000

In [121]:
model1 = tf.keras.models.Sequential()
model1.add(tf.keras.layers.Embedding(60000, 32))
model1.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(32, return_sequences = True)))
model1.add(tf.keras.layers.Reshape((57,64,1)))
model1.add(tf.keras.layers.Conv2D(32, kernel_size = (3,3)))
model1.add(tf.keras.layers.MaxPooling2D(4))
model1.add(tf.keras.layers.Conv2D(32, kernel_size = (4,4)))
model1.add(tf.keras.layers.MaxPooling2D(3))
model1.add(tf.keras.layers.Flatten() )
model1.add(tf.keras.layers.Dense(100, activation = 'relu'))
model1.add(tf.keras.layers.Dense(1, activation = 'sigmoid'))

In [122]:
model1.compile( optimizer = 'adam', loss='binary_crossentropy',metrics=['accuracy'])

In [123]:
model1.fit(xtrain,ytrain,validation_split=0.2,epochs = 3 )

Train on 1194640 samples, validate on 298660 samples
Epoch 1/3
1194640/1194640 [==============================] - 4318s 4ms/sample - loss: 0.4224 - accuracy: 0.8053 - val_loss: 0.3952 - val_accuracy: 0.8207
Epoch 2/3
1194640/1194640 [==============================] - 4322s 4ms/sample - loss: 0.3685 - accuracy: 0.8363 - val_loss: 0.3881 - val_accuracy: 0.8256
Epoch 3/3
1194640/1194640 [==============================] - 3441s 3ms/sample - loss: 0.3400 - accuracy: 0.8518 - val_loss: 0.3917 - val_accuracy: 0.8257


In [ ]:
model.save(r'C:\Users\Vinayak Sidharth\Documents\TWITTER_HAPPINESS.model')

In [82]:
o = tf.keras.layers.Conv2D(32, kernel_size = (3,3)) (ii)
t = tf.keras.layers.MaxPooling2D(2)(o)
o2 = tf.keras.layers.Conv2D(32, kernel_size = (3,3))(o)
t2 = tf.keras.layers.MaxPooling2D(2)(o2)
r = tf.keras.layers.Reshape((12,-1))(t2)
l = tf.keras.layers.LSTM(200)(r)
                           

In [83]:
l

<tf.Tensor: shape=(2, 200), dtype=float32, numpy=
array([[-0.17850307, -0.04180878,  0.19274467,  0.46111742,  0.21713682,
        -0.13148668, -0.35039666,  0.2407388 , -0.3775557 ,  0.016915  ,
         0.23292209, -0.08115608, -0.35807097,  0.14464569, -0.10044456,
        -0.08599912,  0.07659259,  0.18297964,  0.17320439,  0.11539391,
         0.25767967, -0.0737422 ,  0.361597  ,  0.08898338,  0.36080888,
         0.09674861,  0.18770443,  0.13439932,  0.11611309,  0.15281731,
        -0.09970555, -0.1518358 ,  0.05167245, -0.3590743 , -0.37093076,
        -0.1653896 ,  0.22919658, -0.20361447,  0.244571  , -0.1594035 ,
         0.00979177, -0.12851354, -0.19015309,  0.10581996,  0.2849481 ,
        -0.21584071,  0.30328158,  0.12578142,  0.37049025, -0.16072497,
         0.47577855,  0.19156227, -0.21565427, -0.04388008, -0.34711945,
        -0.19096184,  0.42099   , -0.02910922, -0.27494785,  0.01565453,
         0.3126618 , -0.21356277,  0.00831184, -0.12144018, -0.36951834,
 

In [100]:
modelp = tf.keras.models.Sequential()
modelp.add(tf.keras.layers.Conv2D(32, kernel_size = (3,3)))
modelp.add(tf.keras.layers.MaxPooling2D(4))
modelp.add(tf.keras.layers.Conv2D(32, kernel_size = (4,4)))
modelp.add(tf.keras.layers.MaxPooling2D(3))
modelp.add(tf.keras.layers.Flatten())
modelp.compile(optimizer = 'adam', metrics=['accuracy'], loss='binary_crossentropy' )

In [101]:
ch = modelp.predict(ii)

In [102]:
ch.shape

(2, 384)

In [61]:
ii = tf.random.normal((2,57,64,1))

In [24]:
oon = tf.keras.layers.Conv2D(32, kernel_size = (4,4))(ii)

In [74]:
ss11 = tf.random.normal((2,12,6))

In [46]:
x = np.array([[1,2,3,4,1,5,33],[5,5,3,2,2,1,2]])

In [47]:
po = tf.keras.layers.Embedding(34,3)(x)

In [48]:
ss = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(3, return_sequences = True))(po)

In [75]:
nss =  tf.keras.layers.LSTM(12)(ss11)

In [103]:
popo = tf.keras.layers.Reshape((7,6,1))(ss)

In [111]:
conv = tf.keras.layers.Conv2D(32, kernel_size = (2,2))(popo)

In [115]:
mx = tf.keras.layers.MaxPooling2D(2)(conv)

In [ ]:
crz = tf.kears.LSTM(128)

In [25]:
ls1 = tf.keras.layers.LSTM(12, return_sequences = True)

In [28]:
ls2 = tf.keras.layers.LSTM(12, go_backwards = True,return_sequences = True ) 

In [29]:
ss1 = tf.keras.layers.Bidirectional(ls1,backward_layer = ls2 )

In [56]:
nss

<tf.Tensor: shape=(2, 12), dtype=float32, numpy=
array([[-0.01963948,  0.4092062 ,  0.22047268,  0.09375506, -0.01355213,
         0.11491966,  0.39352652,  0.10109936, -0.09950218, -0.39432216,
         0.2971056 , -0.01266266],
       [ 0.19200867,  0.42786616, -0.11345592,  0.19756623,  0.08415218,
        -0.67005587,  0.05958585,  0.36883512,  0.06555943, -0.22092949,
         0.02697607,  0.7324941 ]], dtype=float32)>

In [26]:
oon[0]

<tf.Tensor: shape=(54, 61, 32), dtype=float32, numpy=
array([[[ 4.15695995e-01,  1.34814307e-01, -2.56268322e-01, ...,
         -2.96962231e-01,  1.19975910e-01, -4.13211249e-03],
        [-8.22474137e-02,  3.62410665e-01, -3.41286689e-01, ...,
          1.38616666e-01,  1.59383163e-01,  8.86916220e-02],
        [-4.53193158e-01,  1.38031036e-01,  2.64336020e-01, ...,
          9.78679806e-02,  8.74541700e-03, -2.40361646e-01],
        ...,
        [ 1.38853326e-01, -3.60384643e-01, -1.55296460e-01, ...,
         -3.73118013e-01, -4.50705588e-01, -1.73816517e-01],
        [ 5.91769516e-02, -1.40768617e-01,  1.67472258e-01, ...,
         -2.49137402e-01, -9.36683193e-02, -8.58984068e-02],
        [-2.23036915e-01, -5.01346648e-01,  3.20178002e-01, ...,
         -4.92659390e-01, -1.44732133e-01, -2.46578366e-01]],

       [[ 7.10738674e-02, -1.07183725e-01,  5.58869652e-02, ...,
         -9.28430036e-02, -1.78815231e-01, -3.69963259e-01],
        [-2.84254521e-01, -3.48172300e-02, -2.754

In [116]:
mx[0]

<tf.Tensor: shape=(3, 2, 32), dtype=float32, numpy=
array([[[ 3.46815563e-03,  2.42477329e-03,  8.13817722e-04,
          5.22070564e-04,  1.71560165e-03,  1.26885111e-03,
          6.43325213e-04,  1.02765829e-04,  4.22539219e-04,
          1.40528334e-03,  4.40615742e-03,  1.71834696e-03,
          2.22007022e-03,  1.71630993e-03,  2.05257977e-03,
         -4.43275319e-04,  9.69189394e-04,  2.58246693e-03,
          6.13711192e-04,  1.11426914e-03,  2.68391706e-03,
          1.07012922e-03,  2.41354248e-03,  7.73899781e-04,
          1.61211018e-03,  1.95597950e-03,  1.02633773e-03,
          1.14041101e-03,  2.34635919e-03,  3.41984699e-03,
          1.52533583e-03,  9.63777420e-04],
        [ 9.34939191e-04,  2.19384232e-03,  1.25449407e-03,
          1.32975436e-03,  1.55003532e-03,  4.79677925e-04,
          2.46364693e-03,  2.91221892e-03,  1.18723919e-03,
          1.01027207e-03,  1.96201866e-03,  1.37090962e-03,
          1.37157051e-03,  1.55439891e-03,  3.67919938e-03,
    

In [113]:
conv[0]

<tf.Tensor: shape=(6, 5, 32), dtype=float32, numpy=
array([[[ 2.08285660e-03, -1.50197046e-03, -2.74775736e-03,
         -2.08304590e-03,  1.71560165e-03,  2.70660123e-04,
          5.31521975e-04,  1.02765829e-04, -2.31776488e-04,
         -1.11837508e-04,  9.13429423e-04,  1.71834696e-03,
          9.37303848e-05, -1.38692354e-04,  6.46265573e-04,
         -4.43275319e-04,  9.69189394e-04,  2.58246693e-03,
          6.13711192e-04,  7.82928953e-04, -9.93405236e-04,
         -3.64613690e-04,  1.85153598e-03,  4.92489606e-04,
          1.20665517e-03,  1.95597950e-03, -7.73296342e-04,
          1.27555002e-04,  2.34635919e-03,  9.91159235e-04,
          1.52533583e-03, -9.51796479e-04],
        [-2.35191267e-03,  2.42477329e-03,  8.13817722e-04,
         -3.63516185e-04, -4.35789378e-04,  1.26885111e-03,
         -6.99442171e-05, -2.89002783e-03, -1.97286112e-03,
         -8.12340295e-04, -3.25089530e-03, -1.63869292e-03,
         -1.26726634e-03, -1.28518161e-03,  2.05257977e-03,
    

In [105]:
popo[0]

<tf.Tensor: shape=(7, 6, 1), dtype=float32, numpy=
array([[[ 0.00172731],
        [ 0.01049861],
        [-0.00816511],
        [ 0.00154627],
        [-0.00031095],
        [ 0.00969618]],

       [[-0.00518938],
        [ 0.00534161],
        [-0.00530425],
        [ 0.00502009],
        [-0.00150965],
        [ 0.01246564]],

       [[-0.00654637],
        [-0.00953049],
        [-0.00409291],
        [ 0.01060599],
        [-0.00934777],
        [ 0.01284254]],

       [[ 0.00026613],
        [-0.01842894],
        [-0.00470491],
        [ 0.00820029],
        [-0.0097271 ],
        [ 0.00784253]],

       [[ 0.00513819],
        [-0.00367379],
        [-0.01203322],
        [ 0.00150345],
        [-0.00242491],
        [ 0.00384084]],

       [[ 0.0051789 ],
        [-0.00964824],
        [-0.00935502],
        [ 0.00477418],
        [-0.00457334],
        [ 0.00505277]],

       [[ 0.00982496],
        [-0.00653577],
        [-0.01515239],
        [ 0.00325249],
        [-0.00358

In [100]:
ss[0]

<tf.Tensor: shape=(7, 6), dtype=float32, numpy=
array([[ 0.00172731,  0.01049861, -0.00816511,  0.00154627, -0.00031095,
         0.00969618],
       [-0.00518938,  0.00534161, -0.00530425,  0.00502009, -0.00150965,
         0.01246564],
       [-0.00654637, -0.00953049, -0.00409291,  0.01060599, -0.00934777,
         0.01284254],
       [ 0.00026613, -0.01842894, -0.00470491,  0.00820029, -0.0097271 ,
         0.00784253],
       [ 0.00513819, -0.00367379, -0.01203322,  0.00150345, -0.00242491,
         0.00384084],
       [ 0.0051789 , -0.00964824, -0.00935502,  0.00477418, -0.00457334,
         0.00505277],
       [ 0.00982496, -0.00653577, -0.01515239,  0.00325249, -0.00358495,
         0.00295588]], dtype=float32)>

In [31]:
ls1(po)[0]

<tf.Tensor: shape=(7, 12), dtype=float32, numpy=
array([[-4.5859260e-03,  4.1419123e-03, -3.9950535e-03, -3.9309454e-03,
        -4.5419531e-03,  1.4804996e-03, -6.6988787e-04,  2.4446666e-03,
         7.0754241e-04, -1.8825310e-03,  3.6247489e-03,  3.9117392e-03],
       [-4.9225986e-03,  6.2483917e-03, -4.0093525e-03, -3.2098610e-03,
        -5.0666383e-03,  3.0881627e-03,  8.7517925e-04,  2.4149537e-03,
         2.5902595e-03, -2.8942986e-03,  5.9694303e-03,  5.3185928e-03],
       [-4.8835012e-03,  6.7893476e-03, -3.3952864e-03, -4.1656708e-03,
        -6.7955987e-03,  1.3885917e-03, -1.3306320e-03,  1.5843321e-05,
         4.0122624e-03, -9.8846457e-04,  4.5822929e-03,  4.6087201e-03],
       [-3.9847251e-03,  6.9678500e-03, -2.5197077e-03, -2.7062034e-03,
        -6.0865325e-03,  1.5815347e-04, -7.8103767e-04,  6.2760839e-04,
         3.5912071e-03, -1.0547325e-03,  3.7951423e-03,  3.3432255e-03],
       [-7.2109047e-03,  1.0599938e-02, -5.2320333e-03, -5.1172976e-03,
        -9.

In [32]:
ls2(po)[0]

<tf.Tensor: shape=(7, 12), dtype=float32, numpy=
array([[-4.8207929e-03, -5.5268663e-03, -5.0336309e-04,  3.0486949e-03,
         3.8747871e-03, -3.5070907e-04,  4.8117852e-03,  3.5238527e-03,
        -4.7660461e-03, -2.6722893e-03, -2.8781400e-03,  3.0135473e-03],
       [-4.8168711e-03, -6.6080294e-03, -4.8483959e-03,  5.3076847e-03,
         4.8843608e-03, -1.6133311e-03,  6.5904721e-03,  2.0709494e-03,
        -3.1312630e-03, -5.9276172e-03, -3.7902971e-03,  5.2241812e-04],
       [-1.3033663e-04,  3.8823663e-04, -4.8400629e-03,  2.4611286e-03,
         1.6493949e-03, -1.8319922e-03,  1.5848908e-03, -1.9231375e-03,
         2.1805372e-03, -3.2670670e-03, -8.5418072e-04, -2.7869632e-03],
       [-9.3170529e-06,  1.0714321e-03, -3.8194831e-03,  2.0993366e-03,
         1.4106495e-03, -1.3677820e-03,  1.2276894e-03, -2.1351066e-03,
         2.5099092e-03, -2.2294826e-03, -1.8930553e-04, -3.2355292e-03],
       [-2.0663647e-04,  3.6244995e-03, -5.6749186e-04,  1.2817255e-03,
         4.

In [33]:
ss1(po)[0]

<tf.Tensor: shape=(7, 24), dtype=float32, numpy=
array([[ 2.6062552e-03,  2.3405182e-03, -2.0846822e-03, -2.9089998e-03,
         1.2997246e-03,  1.2247565e-03, -1.5384082e-03, -2.4515875e-03,
        -4.1957893e-03, -4.6856711e-03, -8.0710772e-04,  5.3328359e-03,
         5.0438400e-03,  6.5406249e-03,  1.0294570e-04, -2.5201186e-03,
        -3.6248195e-03,  4.5823422e-04, -4.4752415e-03, -4.7675166e-03,
         6.4276168e-03,  3.2157628e-03,  3.7146113e-03, -5.5357222e-03],
       [ 2.7017349e-03,  1.4666998e-03, -2.0764961e-03, -3.0350063e-03,
         8.4387965e-04,  3.6212319e-04, -1.4760341e-03, -2.0500936e-03,
        -3.8252405e-03, -5.8187088e-03, -2.7724271e-04,  6.6838609e-03,
         1.6985327e-03,  3.5951475e-03, -1.8419886e-04, -9.7591063e-04,
        -5.1176461e-04, -5.5250194e-04, -1.9889877e-03, -2.1092191e-03,
         3.0011253e-03,  1.7323488e-03,  1.7169389e-03, -2.8735455e-03],
       [ 2.3099859e-03,  2.6471908e-03, -4.2487012e-04, -3.5187907e-03,
        -2.26

In [17]:

model = tf.keras.models.Sequential()
forward_layer = tf.keras.layers.LSTM(10, return_sequences=True)
backward_layer = tf.keras.layers.LSTM(10, activation='relu', return_sequences=True,
                       go_backwards=True)
model.add(tf.keras.layers.Bidirectional(forward_layer, backward_layer=backward_layer,
                        input_shape=(7, 3) ))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')


In [18]:
model.predict(po)

array([[[ 3.32372496e-03, -2.26440316e-04,  3.84904048e-03,
          3.23258981e-04, -4.63325670e-03,  1.65402470e-03,
          1.33806607e-03,  3.52353789e-03,  2.61766277e-03,
          3.51763214e-03,  1.90172705e-03,  4.53045638e-03,
          2.03589589e-04,  8.54538381e-03,  4.58517432e-04,
          5.26618212e-03,  2.00293935e-03,  7.55253481e-03,
          1.09488203e-03,  5.12369722e-03],
        [ 3.67623940e-03, -1.80645788e-03,  4.77306452e-03,
          2.04672525e-03, -5.28206490e-03,  6.95884752e-04,
          2.31352332e-03,  4.62798681e-03,  3.31057748e-03,
          3.55596212e-03,  2.02928926e-03,  2.44625541e-03,
          2.77590210e-04,  4.80398722e-03,  6.26902445e-04,
          4.00173431e-03,  2.75418791e-03,  4.22410574e-03,
          1.50121842e-03,  2.84629548e-03],
        [ 3.23628518e-03,  3.57419020e-04,  6.33099256e-03,
          7.08287349e-04, -3.73584544e-03,  1.06553384e-03,
         -4.67123609e-05,  4.98441933e-03,  4.39553522e-03,
          1.

TypeError: bad operand type for unary -: 'list'